### ISSUE TITLE
Dodanie materiałów źródłowych JS

### ISSUE THREAD

**Issue by Cezaryx** [Boczolaf/JSTableVisualization#5]
- [ ] Dodano

**Comment by wojnicki** [comment]
Art. przeglądowy: [tt-xtt-cndt-par.pdf](https://github.com/Boczolaf/JSTableVisualization/files/4448835/tt-xtt-cndt-par.pdf)

Bardziej szczegółowo z omówieniem przykładu: 
[2012-scr-eng.pdf](https://github.com/Boczolaf/JSTableVisualization/files/4448838/2012-scr-eng.pdf)
